### ISSUE TITLE
It does not work for me

### ISSUE THREAD

**Issue by depeton** [dkanada/jellyfin-plugin-intros#17]
The plugin looks super good, I still haven't managed to get it to work.
You can publish a compiled version.

**Comment by dkanada** [comment]
Can you try installing it again? I made some changes to the file.

**Comment by depeton** [comment]
Thanks for your answer, I already tried it and it still doesn't work for me, the intro starts before the video, right?
It does not appear to me anywhere, but if I select it and it is saved.

**Comment by ilco3** [comment]
i am having the same problem -reinstald it 2ce -and it is till no working

**Comment by dkanada** [comment]
It should be working fine now, can anyone confirm?

**Comment by depeton** [comment]
What's up friend.
I just tested version 1.2.0.0 in the latest version of Jellyfin.

It doesn't work for me, I don't know what else to do.

**Comment by dkanada** [comment]
Just to confirm, this is with the 10.6.4 version of the server? Windows or Linux?

**Comment by depeton** [comment]
10.6.4 Ubuntu bro

**Comment by dkanada** [comment]
I pushed one more update, can you install it and try again?

**Comment by depeton** [comment]
I just tried and it still doesn't work.

When I select the video and click save, it doesn't save.

**Comment by Ishannaik** [comment]
Yep doesn't work for me too on ubuntu and 10.6.4 installed from Repository URL

**Comment by dkanada** [comment]
I had another developer confirm it was working with the latest update, so I think it's a browser cache issue now.

**Comment by Ishannaik** [comment]
Has there been any fix out yet?

**Comment by depeton** [comment]
I just tried it on a new machine with a new and an old library and I can't get it to work for me

**Comment by dkanada** [comment]
What browser are you using?

**Comment by Ishannaik** [comment]
I've tried it on chrome/edge/jellyfifn tv app/jellyfin android app and I've asked it doesn't work anyone on my jellyfin server I think it's an ubuntu issue(might be permissions?) as everyone having this issue here is on ubuntu can you guys confirm?

**Comment by Ishannaik** [comment]
Has there been any fix pushed out yet?

**Comment by ilco3** [comment]
i am running a dedicated  debian 9 server   -same problem

Op ma 14 dec. 2020 om 18:28 schreef Ishan <notifications@github.com>:

**Comment by dkanada** [comment]
I've tested this and it works for me, so I'll need more information before I can do anything about it. Can someone try to save the settings with the browser console open and see what happens? What about manually editing the XML config directly and then checking to see if they show up on the web client?

**Comment by Ishannaik** [comment]
The settings get saved but the intros aren't there 
When I click on save with the console open this comes up
`Requesting URL without automatic networking: http://removed:xxxx/Plugins/9482dc3b-48aa-4d3b-8224-9128d1e8e0cd/Configuration`

**Comment by Ishannaik** [comment]
Still need help with XML Config

**Comment by Ishannaik** [comment]
<?xml version="1.0"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Intro>482298222</Intro>
  <Resolution>1080</Resolution>
  <Random>false</Random>
  <Id>00000000-0000-0000-0000-000000000000</Id>
</PluginConfiguration>
This is my XML Config what do I set it to?

**Comment by ilco3** [comment]
ive just installed the plugin on my fresh jellyfin docker instance .on my  debian 10 server 
it still wont load

**Comment by depeton** [comment]
It already worked in 1.3.0, it's great.
When I can I will provide some support.
Excellent work.

**Comment by Goaff** [comment]
I ran into the exact same issue ( /Intros 500 (Internal Server Error) ).
Any idea on how to fix this ?
