### ISSUE TITLE
Crash or Blurred on own intros uploaded on Vimeo using (Exoplayer on Firestick) 

### ISSUE THREAD

**Issue by butts136** [dkanada/jellyfin-plugin-intros#56]
HI,

I did a few times my own intros video uploaded on Vimeo and it was working perfectly.
I have done a video but it's always crashing on Exoplayer and it's blurred at 360p on LibVLC.
I have tried encoding few different light format, mp4, avi, mov, H.264, HEVC, try convert video via online converter but still crashing on vimeo and crashing even if I put them in a directory directly.

Wich codec, format should i use for Perfect compatibility ?

Here's my last edit that i'm trying to put as intro : https://vimeo.com/manage/videos/759209040.

I used free template from Youtube, Edit them in After Effects, after I need to encode because the video weight 170MB for 12 Seconds, and upload it to vimeo. I wait until Vimeo finish all is optimization, Took the video ID and try it, And crash or disgusting 360p.
I did some working without problems but now, it's almost impossible.

Thanks

**Comment by butts136** [comment]
I thinks it's the part when it's crashing so maybe it can help.


[2022-10-11 18:29:23.786 +00:00] [INF] [111] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "Alexandre Butts". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2022-10-11 18:29:23.788 +00:00] [INF] [111] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="AndroidTV-libVLC", Path="/config/cache/intros/759227584-360.mp4", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/e61d8aab-4b45-4d00-bdf8-7a0a6518c383/stream.mov?MediaSourceId=e61d8aab4b454d00bdf87a0a6518c383&Static=true&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&api_key=<token>&Tag=ebcf67b87d3afd796df86e73c1fa21b1"
[2022-10-11 18:29:23.948 +00:00] [INF] [121] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "Alexandre Butts". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2022-10-11 18:29:23.949 +00:00] [INF] [121] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="AndroidTV-ExoPlayer", Path="/config/cache/intros/759227584-360.mp4", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/e61d8aab-4b45-4d00-bdf8-7a0a6518c383/stream.mov?MediaSourceId=e61d8aab4b454d00bdf87a0a6518c383&Static=true&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&api_key=<token>&Tag=ebcf67b87d3afd796df86e73c1fa21b1"
[2022-10-11 18:29:24.181 +00:00] [INF] [107] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Adding playback tracker : 3d142db4fd32873b4d64f02bbb5c3934fbb72625-3774b155894048d2a5bcb72b94464def-e61d8aab4b454d00bdf87a0a6518c383
[2022-10-11 18:29:24.181 +00:00] [INF] [107] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Start Event : 10/11/2022 18:29:24
[2022-10-11 18:29:24.181 +00:00] [INF] [107] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Creating StartPlaybackTimer Task
[2022-10-11 18:29:24.181 +00:00] [INF] [106] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Entered
[2022-10-11 18:29:24.950 +00:00] [INF] [106] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "3d142db4fd32873b4d64f02bbb5c3934fbb72625-3774b155894048d2a5bcb72b94464def-e61d8aab4b454d00bdf87a0a6518c383"
[2022-10-11 18:29:25.804 +00:00] [INF] [115] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "TW96aWxsYS81LjAgKFNNQVJULVRWOyBMaW51eDsgVGl6ZW4gNS41KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBTYW1zdW5nQnJvd3Nlci8zLjAgQ2hyb21lLzY5LjAuMzQ5Ny4xMDYgVFYgU2FmYXJpLzUzNy4zNnwxNjI1NjcwNjM5Mzg2-eea6d6cc4c1c45029275a6684a0ffb1d-f09dbbdbbd4f980ca69320cb5ce58dea"
[2022-10-11 18:29:28.989 +00:00] [WRN] [106] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "46.232.211.10" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2022-10-11 18:29:28.991 +00:00] [INF] [106] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "46.232.211.10" closed
[2022-10-11 18:29:44.182 +00:00] [INF] [54] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session Not Found
[2022-10-11 18:29:44.182 +00:00] [INF] [54] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Exited
[2022-10-11 18:29:46.802 +00:00] [INF] [113] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "TW96aWxsYS81LjAgKFNNQVJULVRWOyBMaW51eDsgVGl6ZW4gNS41KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBTYW1zdW5nQnJvd3Nlci8zLjAgQ2hyb21lLzY5LjAuMzQ5Ny4xMDYgVFYgU2FmYXJpLzUzNy4zNnwxNjI1NjcwNjM5Mzg2-eea6d6cc4c1c45029275a6684a0ffb1d-f09dbbdbbd4f980ca69320cb5ce58dea"
[2022-10-11 18:29:52.065 +00:00] [WRN] [106] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://butts136.morpheus.usbx.me/jellyfin/Videos/f5ca60af4701e8ffaa567544bfe26a94/stream?Static=true&mediaSourceId=f5ca60af4701e8ffaa567544bfe26a94&deviceId=01-00-DE-36-02-00-05-EA-03-00-F1-9D-04-00-CA-71-05-00-6A-D6-07-00-9A-22-08-00-43-C9-09-00-94-99-01-00-C6-15-02-00-A0-00-03-00-A9-4D-04-00-EE-2A-05-00-B5-0D-07-00-6D-A4-08-00-F1-AF-09-00-49-B1&api_key=1cfd1218b18d4cffbd920429964eb4ce" to "46.232.211.10" in 0:00:00.7626018 with Status Code 206
[2022-10-11 18:29:53.678 +00:00] [WRN] [102] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://butts136.morpheus.usbx.me/jellyfin/Videos/7ab2e2ff654ddef5a5b1ab571a404ec8/stream?Static=true&mediaSourceId=7ab2e2ff654ddef5a5b1ab571a404ec8&deviceId=01-00-DE-36-02-00-05-EA-03-00-F1-9D-04-00-CA-71-05-00-6A-D6-07-00-9A-22-08-00-43-C9-09-00-94-99-01-00-C6-15-02-00-A0-00-03-00-A9-4D-04-00-EE-2A-05-00-B5-0D-07-00-6D-A4-08-00-F1-AF-09-00-49-B1&api_key=1cfd1218b18d4cffbd920429964eb4ce" to "46.232.211.10" in 0:00:01.0151255 with Status Code 206
[2022-10-11 18:29:54.451 +00:00] [INF] [54] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2022-10-11 18:29:56.844 +00:00] [WRN] [113] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://butts136.morpheus.usbx.me/jellyfin/Videos/f09dbbdbbd4f980ca69320cb5ce58dea/stream.mkv?Static=true&mediaSourceId=f09dbbdbbd4f980ca69320cb5ce58dea&deviceId=TW96aWxsYS81LjAgKFNNQVJULVRWOyBMaW51eDsgVGl6ZW4gNS41KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBTYW1zdW5nQnJvd3Nlci8zLjAgQ2hyb21lLzY5LjAuMzQ5Ny4xMDYgVFYgU2FmYXJpLzUzNy4zNnwxNjI1NjcwNjM5Mzg2&api_key=3c030bcd4468425ebb45f6f5dc6d086c&Tag=e2daa63ac389418c01bec645eed5c123" to "46.232.211.10" in 0:00:00.8642509 with Status Code 206
[2022-10-11 18:30:06.453 +00:00] [INF] [98] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2022-10-11 18:30:06.806 +00:00] [INF] [112] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "TW96aWxsYS81LjAgKFNNQVJULVRWOyBMaW51eDsgVGl6ZW4gNS41KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBTYW1zdW5nQnJvd3Nlci8zLjAgQ2hyb21lLzY5LjAuMzQ5Ny4xMDYgVFYgU2FmYXJpLzUzNy4zNnwxNjI1NjcwNjM5Mzg2-eea6d6cc4c1c45029275a6684a0ffb1d-f09dbbdbbd4f980ca69320cb5ce58dea"
[2022-10-11 18:30:10.167 +00:00] [INF] [93] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "46.232.211.10" request
[2022-10-11 18:30:18.032 +00:00] [INF] [54] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Video", Name: "Joyeux", Path: "/config/cache/intros/759209040-360.mp4", Id: 959c499c-5b0a-44e4-a04b-76a1771de8c2
[2022-10-11 18:30:18.042 +00:00] [WRN] [54] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://butts136.morpheus.usbx.me/jellyfin/Users/3774b155-8940-48d2-a5bc-b72b94464def/Items/f6b196bdb1799efca2f81132b9e31010/Intros?format=json" to "46.232.211.10" in 0:00:00.9285044 with Status Code 200
[2022-10-11 18:30:18.453 +00:00] [INF] [112] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
[2022-10-11 18:30:19.401 +00:00] [INF] [112] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "Alexandre Butts". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2022-10-11 18:30:19.401 +00:00] [INF] [112] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="AndroidTV-libVLC", Path="/config/cache/intros/759209040-360.mp4", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/6bdb323a-91d8-4079-8ff7-1086b8715d0a/stream.mov?MediaSourceId=6bdb323a91d840798ff71086b8715d0a&Static=true&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&api_key=<token>&Tag=170daf3cdbd8cce71bc5dd4558acf75f"
[2022-10-11 18:30:19.692 +00:00] [INF] [98] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "Alexandre Butts". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2022-10-11 18:30:19.692 +00:00] [INF] [98] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="AndroidTV-ExoPlayer", Path="/config/cache/intros/759209040-360.mp4", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/6bdb323a-91d8-4079-8ff7-1086b8715d0a/stream.mov?MediaSourceId=6bdb323a91d840798ff71086b8715d0a&Static=true&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&api_key=<token>&Tag=170daf3cdbd8cce71bc5dd4558acf75f"
[2022-10-11 18:30:20.032 +00:00] [INF] [97] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Adding playback tracker : 3d142db4fd32873b4d64f02bbb5c3934fbb72625-3774b155894048d2a5bcb72b94464def-6bdb323a91d840798ff71086b8715d0a
[2022-10-11 18:30:20.032 +00:00] [INF] [97] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Start Event : 10/11/2022 18:30:20
[2022-10-11 18:30:20.033 +00:00] [INF] [97] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Creating StartPlaybackTimer Task
[2022-10-11 18:30:20.033 +00:00] [INF] [101] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Entered
[2022-10-11 18:30:20.792 +00:00] [INF] [112] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "3d142db4fd32873b4d64f02bbb5c3934fbb72625-3774b155894048d2a5bcb72b94464def-6bdb323a91d840798ff71086b8715d0a"
[2022-10-11 18:30:24.820 +00:00] [WRN] [112] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "46.232.211.10" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2022-10-11 18:30:24.824 +00:00] [INF] [112] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "46.232.211.10" closed
[2022-10-11 18:30:26.807 +00:00] [INF] [112] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "TW96aWxsYS81LjAgKFNNQVJULVRWOyBMaW51eDsgVGl6ZW4gNS41KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBTYW1zdW5nQnJvd3Nlci8zLjAgQ2hyb21lLzY5LjAuMzQ5Ny4xMDYgVFYgU2FmYXJpLzUzNy4zNnwxNjI1NjcwNjM5Mzg2-eea6d6cc4c1c45029275a6684a0ffb1d-f09dbbdbbd4f980ca69320cb5ce58dea"

**Comment by butts136** [comment]
I have done few test with lots of videos from vimeo.

There's is three problems i have notice 

P/s : When i talk about crash, it's only on Firestick as far i can say but it's blurred on all devices

1) 90% of the videos from vimeo are downloaded in 360p instead of what we ask, like 1080p. when the video is downloaded in 360p, It's blurred in LibVLC and Exoplayer but Exoplayer crash automaticly.
When it's in the desired resolution, 480, 720, 1080 or more, it's working well on both player without any problems.

2) Like I said, some videos that I have uploaded earlier this year was working and are still working, but if I upload again the same exacte video files on Vimeo, This one is now not working, That's weird,

3) If i took one of my old videos working from vimeo and use it with the local source option, it's in original quality and working on VLC but still crash on ExoPlayer.

I don't understand why it's downloading only in 360p Most of the time,
Probably mixed with ExoPlayer compatibility problem. He can plan the video but not if it is an intro.

Thanks ;)

**Comment by njhughes-01** [comment]
I fixed this issue for myself my using the Vimeo encoding setting on adobe media encoder and placing the files locally. Simply referencing the directory will still make the player crash you have to reference the file directly. 

```/config/intro/intro.mp4```
that has it working on my android and firesticks with exoPlayer

**Comment by butts136** [comment]
Didn't work for me, unfortunatly.

I did encode in h.264 (.mp4) with Vimeo 1080p Fulll HD, Upload the files right to the good place, Point directly to the file instead of th folder but still the same result. Crash the app.

Can you try with another file just to make sure it's not just a lucky shot ? Like I said, from Vimeo, some work and some not work :/

Thanks

**Comment by njhughes-01** [comment]
I completely removed Vimeo from the problem as I ran into the same issue you did in that it would render at different qualities. This also only seems to happen on androidTV for me and I know there are some 10.8.5 issue with the client as the maintainer has told people to roll thier server back to 10.8.4 until they found the issue so we could be chasing ghosts and this could be a client issue

**Comment by butts136** [comment]
As you said, it's probably a client issue.

But there is still a problem with this plugins.

Videos are still downloading in 360p instead of downloading in 1080p or the resolution we asked if we are talking about the vimeo option.

This is probably an issue with the plugins for this part

Thanks

**Comment by njhughes-01** [comment]
I had the android client do the 360p thing to me while watching bobs burgers last night. So for me the issues is even with my own media sometimes unless I force close the app. I think until the issue with the android client is worked out I have no idea what to submit for the pr as I don't even get the same errors in the log each time. 
I know that's not super helpful but I rolled back to 10.8.4 and didn't have it happen again so I do think it has something to do with the work that has to be done on the Tvclient

**Comment by butts136** [comment]
I have found a way to make it work. I really think the problem comes from the Plugins more than the Jellyfin client or server.

You can try it my way.

I take one of my working video link from vimeo.
For exemple, this ont is working (https://vimeo.com/manage/videos/637308309)
when I go to the local folder. I can found this : /.apps/jellyfin/cache/intros/637308309-1080.mp4

I just replace LOCALLY my file with the new file and rename it exactly the same and now it works.
Only problem, it takes the title of my Vimeo video. I just changed it before doing the trick.

1) Find one of your video that work in all format from vimeo
2) Change video title to what you want
3) Use the Vimeo ID for your the Jellyfin Plugins
4) Replace the video file with the one you want
5) Name it exactly like the video that was in place ex: (637308309-1080.mp4)
6) Try it

I wish something can be made for the next update, maybe the possibility to use youtube if vimeo doesn't support constant download in more than 360p.

Thanks

**Comment by njhughes-01** [comment]
Mine works fine once I found the right codec with a local file I made like 4 different reals. Grab your log next time you have a crash and post it

**Comment by butts136** [comment]
Now, it's impossible to use Local Sources and not all vimeo videos is downloaded so the plugins is almost useless now :/

**Comment by njhughes-01** [comment]
Can confirm this just crashes samsung tvs i had to remove to instability i would remove the plunin if you hope to have a good exp

**Comment by butts136** [comment]
For me, I found a way to make it work again yesturday, but it's blurred on Desktio browser. Good on firestick but crashing after 1 time on 3.

I wish Jellyfin will develop something Native soon :/ 

We got no answer from the coder here unfortunately.
